services: 
  bitcoind: 
    image: lncm/bitcoind:v27.0
    container_name: caravan_e2e_bitcoind
    ports:
      - "18443:18443"
    volumes:
      - ./bitcoin.conf:/data/.bitcoin/bitcoin.conf:ro
    healthcheck:
      test: ["CMD", "bitcoin-cli", "-regtest", "getblockchaininfo"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - caravan-e2e

  nginx:
    image: nginx:alpine
    container_name: caravan-e2e-nginx 
    ports: 
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on: 
      bitcoind:
        condition: service_healthy
    networks:
     - caravan-e2e

networks:
  caravan-e2e:
    driver: bridge

    
