name: Test

on: [push, pull_request]

permissions:
  contents: read
  checks: write

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["20.x"]
    # To use Turborepo Remote Caching, set the following environment variables for the job.
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Run tests
        run: |
          npx turbo run ci

  # Run e2e tests only for coordinator-related changes
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check for coordinator changes
        uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            coordinator:
              - 'apps/coordinator/**'
              - 'packages/**'
              - '.github/workflows/e2e.yml'
              - 'package*.json'

      - name: Run E2E Tests
        if: steps.changes.outputs.coordinator == 'true'
        uses: ./.github/workflows/e2e.yml

      - name: Skip E2E Tests
        if: steps.changes.outputs.coordinator != 'true'
        run: |
          echo "No coordinator changes detected, skipping E2E tests"
          echo "Changed files:"
          git diff --name-only ${{ github.event.before }} ${{ github.event.after }} || echo "No diff available"

  check-coordinator:
    runs-on: ubuntu-latest
    outputs:
      will-test: ${{ steps.check.outputs.will-test }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # changeset status cant be used until https://github.com/changesets/changesets/issues/1055 is fixed
      - name: Check if caravan-coordinator needs testing
        id: check
        run: |
          # Check if caravan-coordinator is in the changesets
          if grep -h '^"caravan-coordinator":' .changeset/*.md; then
            echo "will-test=true" >> $GITHUB_OUTPUT
            echo "✅ caravan-coordinator will be tested"
          else
            echo "will-test=false" >> $GITHUB_OUTPUT
            echo "❌ caravan-coordinator will not be tested"
          fi

  docker:
    name: Verify Docker Image Builds
    needs: check-coordinator
    runs-on: ubuntu-latest
    if: needs.check-coordinator.outputs.will-test == 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Test Docker image build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./apps/coordinator/Dockerfile
          push: false
