name: Test

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: 

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["20.x"]
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Run CI Tasks
        run: |
          npx turbo run ci
        env:
          NODE_ENV: test

      - name: Run Tests with Coverage
        run: npm run test:coverage

      # - name: Merge Coverage Reports
      #   run: npx lcov-result-merger 'apps/*/coverage/lcov.info packages/*/coverage/lcov.info' './coverage/lcov.info'

      # - name: Upload to Codecov
      #   uses: codecov/codecov-action@v4
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     files: ./coverage/lcov.info
      #     fail_ci_if_error: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Check Coverage Disable
        run: python .github/workflows/scripts/code_coverage_disable_check.py --directory apps packages